spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/SPRINGBOOTSTUDENT
spring.datasource.username=root
spring.datasource.password=faizy786@
spring.jpa.hibernate.ddl-auto = update
